INSERT INTO kategoria VALUES(null, 'AGD');
INSERT INTO kategoria VALUES(null, 'bakalie');
INSERT INTO kategoria VALUES(null, 'grzyby');
INSERT INTO kategoria VALUES(null, 'jaja');
INSERT INTO kategoria VALUES(null, 'komputery');
INSERT INTO kategoria VALUES(null, 'maszyny');
INSERT INTO kategoria VALUES(null, 'mięso');
INSERT INTO kategoria VALUES(null, 'nabiał');
INSERT INTO kategoria VALUES(null, 'nawozy i opryski');
INSERT INTO kategoria VALUES(null, 'obuwie');
INSERT INTO kategoria VALUES(null, 'ogrodnictwo');
INSERT INTO kategoria VALUES(null, 'opakowania');
INSERT INTO kategoria VALUES(null, 'owoce');
INSERT INTO kategoria VALUES(null, 'pasze');
INSERT INTO kategoria VALUES(null, 'pieczywo');
INSERT INTO kategoria VALUES(null, 'przetwory');
INSERT INTO kategoria VALUES(null, 'rośliny motylkowe');
INSERT INTO kategoria VALUES(null, 'rośliny oleiste');
INSERT INTO kategoria VALUES(null, 'RTV');
INSERT INTO kategoria VALUES(null, 'ryby');
INSERT INTO kategoria VALUES(null, 'słodycze');
INSERT INTO kategoria VALUES(null, 'ubrania');
INSERT INTO kategoria VALUES(null, 'warzywa');
INSERT INTO kategoria VALUES(null, 'zabawki');
INSERT INTO kategoria VALUES(null, 'zboża');
INSERT INTO kategoria VALUES(null, 'ziemniaki');
INSERT INTO kategoria VALUES(null, 'zioła');
INSERT INTO kategoria VALUES(null, 'inne');
